"""add pending actions and audit log tables

Revision ID: 2481df2a70f0
Revises: 26800d559edc
Create Date: 2026-08-08 17:42:00.652673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2481df2a70f0'
down_revision: Union[str, None] = '26800d559edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('decision_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.Enum('EXECUTE_DECISION', 'REPLAY_SIMULATION', name='pending_action_type'), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'EXPIRED', 'EXECUTING', 'COMPLETED', 'FAILED', name='pending_action_status'), nullable=False),
    sa.Column('summary', sa.String(length=1000), nullable=False),
    sa.Column('scenario_key', sa.String(length=80), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_pending_actions_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_pending_actions_decision_id_decisions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_pending_actions_execution_id_executions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['optimization_plans.id'], name=op.f('fk_pending_actions_plan_id_optimization_plans'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_actions'))
    )
    op.create_index(op.f('ix_pending_actions_conversation_id'), 'pending_actions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_pending_actions_decision_id'), 'pending_actions', ['decision_id'], unique=False)
    op.create_index(op.f('ix_pending_actions_plan_id'), 'pending_actions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_pending_actions_status'), 'pending_actions', ['status'], unique=False)
    op.create_table('action_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pending_action_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('decision_id', sa.UUID(), nullable=True),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('result', sa.String(length=1000), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pending_action_id'], ['pending_actions.id'], name=op.f('fk_action_audit_logs_pending_action_id_pending_actions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_audit_logs'))
    )
    op.create_index(op.f('ix_action_audit_logs_conversation_id'), 'action_audit_logs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_action_audit_logs_pending_action_id'), 'action_audit_logs', ['pending_action_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_audit_logs_pending_action_id'), table_name='action_audit_logs')
    op.drop_index(op.f('ix_action_audit_logs_conversation_id'), table_name='action_audit_logs')
    op.drop_table('action_audit_logs')
    op.drop_index(op.f('ix_pending_actions_status'), table_name='pending_actions')
    op.drop_index(op.f('ix_pending_actions_plan_id'), table_name='pending_actions')
    op.drop_index(op.f('ix_pending_actions_decision_id'), table_name='pending_actions')
    op.drop_index(op.f('ix_pending_actions_conversation_id'), table_name='pending_actions')
    op.drop_table('pending_actions')
    # ### end Alembic commands ###
