"""initial schema

Revision ID: 324524b2a813
Revises: 
Create Date: 2026-08-07 08:36:23.838415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '324524b2a813'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clusters')),
    sa.UniqueConstraint('name', name=op.f('uq_clusters_name'))
    )
    op.create_table('scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenarios')),
    sa.UniqueConstraint('key', name=op.f('uq_scenarios_key'))
    )
    op.create_table('racks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('HEALTHY', 'WARNING', 'CRITICAL', 'OFFLINE', name='rack_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], name=op.f('fk_racks_cluster_id_clusters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_racks')),
    sa.UniqueConstraint('cluster_id', 'name', name='uq_rack_cluster_name')
    )
    op.create_index(op.f('ix_racks_cluster_id'), 'racks', ['cluster_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('rack_id', sa.UUID(), nullable=True),
    sa.Column('scenario_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='event_severity'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], name=op.f('fk_events_cluster_id_clusters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], name=op.f('fk_events_rack_id_racks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_events_scenario_id_scenarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_cluster_id'), 'events', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_events_occurred_at'), 'events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_events_rack_id'), 'events', ['rack_id'], unique=False)
    op.create_index(op.f('ix_events_scenario_id'), 'events', ['scenario_id'], unique=False)
    op.create_table('telemetry_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rack_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_celsius', sa.Float(), nullable=False),
    sa.Column('gpu_utilization_pct', sa.Float(), nullable=False),
    sa.Column('power_draw_kw', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], name=op.f('fk_telemetry_records_rack_id_racks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telemetry_records'))
    )
    op.create_index(op.f('ix_telemetry_records_rack_id'), 'telemetry_records', ['rack_id'], unique=False)
    op.create_index(op.f('ix_telemetry_records_recorded_at'), 'telemetry_records', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_records_recorded_at'), table_name='telemetry_records')
    op.drop_index(op.f('ix_telemetry_records_rack_id'), table_name='telemetry_records')
    op.drop_table('telemetry_records')
    op.drop_index(op.f('ix_events_scenario_id'), table_name='events')
    op.drop_index(op.f('ix_events_rack_id'), table_name='events')
    op.drop_index(op.f('ix_events_occurred_at'), table_name='events')
    op.drop_index(op.f('ix_events_cluster_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_racks_cluster_id'), table_name='racks')
    op.drop_table('racks')
    op.drop_table('scenarios')
    op.drop_table('clusters')
    # ### end Alembic commands ###
