"""add optimization plans table and decision plan fields

Revision ID: 64ea115fbd27
Revises: dc15ed44d314
Create Date: 2026-08-08 16:12:11.072696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64ea115fbd27'
down_revision: Union[str, None] = 'dc15ed44d314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



# execution_action_type already exists (created by dc15ed44d314's executions
# table) — autogenerate doesn't know that and would otherwise emit a second
# CREATE TYPE for it here (it fails with DuplicateObjectError), and it also
# doesn't diff enum *values*, so the two new members app.optimization needs
# (FAN_OVERRIDE, NO_ACTION — see app.models.enums.ExecutionActionType) have
# to be added by hand. `create_type=False` on every column below reuses the
# existing type instead of recreating it.
_execution_action_type = postgresql.ENUM(
    'WORKLOAD_MIGRATION', 'COOLING_ADJUSTMENT', 'JOB_DELAY', 'CLUSTER_REBALANCE', 'FAN_OVERRIDE', 'NO_ACTION',
    name='execution_action_type', create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE execution_action_type ADD VALUE IF NOT EXISTS 'FAN_OVERRIDE'")
    op.execute("ALTER TYPE execution_action_type ADD VALUE IF NOT EXISTS 'NO_ACTION'")

    op.create_table('optimization_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=True),
    sa.Column('trigger_rack_id', sa.UUID(), nullable=True),
    sa.Column('trigger_key', sa.String(length=160), nullable=False),
    sa.Column('trigger_reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'FAILED', name='optimization_plan_status'), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('winner_action_type', _execution_action_type, nullable=True),
    sa.Column('winner_overall_score', sa.Float(), nullable=True),
    sa.Column('winner_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], name=op.f('fk_optimization_plans_cluster_id_clusters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_optimization_plans_scenario_id_scenarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trigger_rack_id'], ['racks.id'], name=op.f('fk_optimization_plans_trigger_rack_id_racks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_optimization_plans'))
    )
    op.create_index(op.f('ix_optimization_plans_cluster_id'), 'optimization_plans', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_optimization_plans_scenario_id'), 'optimization_plans', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_optimization_plans_trigger_key'), 'optimization_plans', ['trigger_key'], unique=False)
    op.create_index(op.f('ix_optimization_plans_trigger_rack_id'), 'optimization_plans', ['trigger_rack_id'], unique=False)
    op.add_column('decisions', sa.Column('plan_id', sa.UUID(), nullable=True))
    # server_default so any pre-existing decision rows (from before this
    # column existed) get a valid empty list instead of failing the
    # NOT NULL constraint — the ORM's own default=list (see
    # app.models.decision.Decision) covers every new row from here on.
    op.add_column(
        'decisions',
        sa.Column(
            'alternative_actions', postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"), nullable=False,
        ),
    )
    op.create_index(op.f('ix_decisions_plan_id'), 'decisions', ['plan_id'], unique=False)
    op.create_foreign_key(op.f('fk_decisions_plan_id_optimization_plans'), 'decisions', 'optimization_plans', ['plan_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_decisions_plan_id_optimization_plans'), 'decisions', type_='foreignkey')
    op.drop_index(op.f('ix_decisions_plan_id'), table_name='decisions')
    op.drop_column('decisions', 'alternative_actions')
    op.drop_column('decisions', 'plan_id')
    op.drop_index(op.f('ix_optimization_plans_trigger_rack_id'), table_name='optimization_plans')
    op.drop_index(op.f('ix_optimization_plans_trigger_key'), table_name='optimization_plans')
    op.drop_index(op.f('ix_optimization_plans_scenario_id'), table_name='optimization_plans')
    op.drop_index(op.f('ix_optimization_plans_cluster_id'), table_name='optimization_plans')
    op.drop_table('optimization_plans')
    # Postgres has no ALTER TYPE ... DROP VALUE — the two enum members
    # added in upgrade() are intentionally left in place; harmless if
    # unused, and dropping them would require rebuilding the type from
    # scratch (recreate, migrate every dependent column, drop original).
    # ### end Alembic commands ###
