"""add decisions table

Revision ID: 886e75368c9e
Revises: 324524b2a813
Create Date: 2026-08-07 13:34:24.065470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '886e75368c9e'
down_revision: Union[str, None] = '324524b2a813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=True),
    sa.Column('rule_key', sa.String(length=160), nullable=False),
    # event_severity already exists (created by the initial migration for
    # events.severity) — create_type=False stops Alembic from trying to
    # CREATE TYPE a second time for this column.
    sa.Column(
        'severity',
        postgresql.ENUM('INFO', 'WARNING', 'CRITICAL', name='event_severity', create_type=False),
        nullable=False,
    ),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('reasoning', sa.String(length=2000), nullable=False),
    sa.Column('recommended_action', sa.String(length=500), nullable=False),
    sa.Column('expected_temperature_reduction', sa.Float(), nullable=True),
    sa.Column('expected_power_saving', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('affected_racks', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('affected_jobs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'EXECUTED', 'EXPIRED', name='decision_status'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], name=op.f('fk_decisions_cluster_id_clusters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_decisions_scenario_id_scenarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_index(op.f('ix_decisions_cluster_id'), 'decisions', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_decisions_rule_key'), 'decisions', ['rule_key'], unique=False)
    op.create_index(op.f('ix_decisions_scenario_id'), 'decisions', ['scenario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisions_scenario_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_rule_key'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_cluster_id'), table_name='decisions')
    op.drop_table('decisions')
    # ### end Alembic commands ###
