"""add executions table

Revision ID: dc15ed44d314
Revises: 886e75368c9e
Create Date: 2026-08-07 15:15:57.771521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc15ed44d314'
down_revision: Union[str, None] = '886e75368c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.Enum('WORKLOAD_MIGRATION', 'COOLING_ADJUSTMENT', 'JOB_DELAY', 'CLUSTER_REBALANCE', name='execution_action_type'), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='execution_status'), nullable=False),
    sa.Column('affected_racks', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], name=op.f('fk_executions_cluster_id_clusters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_executions_decision_id_decisions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_executions_scenario_id_scenarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executions'))
    )
    op.create_index(op.f('ix_executions_cluster_id'), 'executions', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_executions_decision_id'), 'executions', ['decision_id'], unique=False)
    op.create_index(op.f('ix_executions_scenario_id'), 'executions', ['scenario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_executions_scenario_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_decision_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_cluster_id'), table_name='executions')
    op.drop_table('executions')
    # ### end Alembic commands ###
